name: Deploy website to Github Pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Deploy to github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: ghpages
          folder: dist
