name: Deploy website to Github Pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Install angular cli
        run: npm i -g @angular/cli

      - name: Deploy to github Pages
        run: ng deploy --base-href=/lol-insights-webiste
